if not(GetLocale() == "deDE") then
    return;
end

local L = WeakAuras.L

-- Options translation
L[" (Channeling)"] = "(Kanalisiert)"
L[" (Healing received increase)"] = " (erhaltene Heilung erhöht)"
L["- Any"] = "Irgendein(e)"
L["- Deathknight 2P Bonus"] = "Todesritter 2er Bonus"
L["- Holy Word: Chastise"] = "- Segenswort: Züchtigung"
L["- Holy Word: Sanctify"] = "- Segenswort: Heiligung"
L["- Holy Word: Serenity"] = "- Segenswort: Epiphanie"
L["- Monk Windwalker 4P Bonus"] = "Mönch Windläufer 4er Bonus"
L["- Paladin Protection 2P Bonus"] = "Paladin Schutz 2er Bonus"
L["- Paladin Retribution 2P Bonus"] = "Paladin Vergeltung 2er Bonus"
L["- T19 Druid Guardian 4P Bonus"] = "Druide T19 Wächter 4er Bonus"
L["- Warlock Affliction 4P/Demonology 2P Bonus"] = "Hexenmeister Gebrechen 2er/Dämonologie 2er Bonus"
L["- Warlock T19 Destruction 4P Bonus"] = "Hexenmeister T19 Zerstörung 2er Bonus"
L["- Warrior 2P Bonus"] = "Krieger 2er Bonus"
L["(Pet)"] = "(Begleiter)"
L["(Water Elemental)"] = "(Wasserelementar)"
L["Ability Charges"] = "Aufladungen der Fähigkeit"
L["Add Triggers"] = "Auslöser hinzufügen"
L["Always Active"] = "Immer aktiv"
L["Back"] = "Zurück"
L["BloodLust/Heroism"] = "Kampfrausch/Heldentum"
L["Buff"] = "Stärkungszauber"
L["buff"] = "Stärkungszauber"
L["Buffs"] = "Stärkungszauber"
L["Cancel"] = "Abbrechen"
L["Cast"] = "Zauberwirken"
L["cooldown"] = "Abklingzeit"
L["Cooldowns"] = "Abklingzeiten"
L["Crimson Vial Item Count"] = "Blutrote Phiole Gegenstandsanzahl"
L["debuff"] = "Schwächungszauber"
L["Debuffs"] = "Schwächungszauber"
L["Enchants"] = "Verzauberungen"
L["General"] = "Allgemein"
L["Health"] = "Gesundheit"
L["Keeps existing triggers intact"] = "Verändert existierende Auslöser nicht"
L["Nimble Brew Item Count"] = "Schlüpfriges Gebräu Gegenstandsanzahl"
L["Pet alive"] = "Begleiter am Leben"
L["Pet Behavior"] = "Begleiterverhalten"
L["PVP Set"] = "PvP-Set"
L["PvP Talents"] = "PvP-Talente"
L["PVP Trinkets"] = "PvP-Schmuckstücke"
L["Replace all existing triggers"] = "Ersetzt alle vorhandenen Auslöser "
L["Replace Triggers"] = "Auslöser ersetzen"
L["Resources"] = "Ressourcen"
L["Resources and Shapeshift Form"] = "Ressourcen und Gestaltwandlungsform"
L["Rooted"] = "Bewegungsunfähig"
L["Runes"] = "Runen"
L["Shapeshift Form"] = "Gestaltwandlungsform"
L["Slowed"] = "Verlangsamt"
L["T19 Healer Trinkets"] = "T19 Heiler-Schmuckstücke"
L["T19 Sets"] = "T19-Sets"
L["T19 Tank Trinkets"] = "T19 Tank-Schmuckstücke"
L["Totem"] = "Totem"
L["Totems"] = "Totems"
L["Unknown Item"] = "Unbekannter Gegenstand"
L["Unknown Spell"] = "Unbekannter Zauber"


